#!/bin/bash

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" == "master" ]; then
    echo "ERROR[a67a539c-3358-4279-8af3-25c6a7ba0bd2]: Commit in \"master\" branch are prohibited!"
    exit 1
fi